### ISSUE TITLE
FOC Control

### ISSUE THREAD

**Issue by davidmuchow** [davidmuchow/botdogs-swerve#3]
## **Feature Request**
**Feature**:
FOC Control     

**Description/Reasoning**:
FOC control will be developed within the TalonFXW class. 
FOC can be expanded on in the comments with research developed by Aidan and any notes he wants to add.

**Comment by davidmuchow** [comment]
Rebased FOC branch to conform with /main
also added built in github tests, meaning that all code must build w/o fail in VS Code before being able to be pushed to main

**Comment by Aidan747** [comment]
did it
